name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dimitriopumay/tp-github-actions_califano-poletti:latest
      
    - name: Build the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker push dimitriopumay/tp-github-actions_califano-poletti:latest
